### ISSUE TITLE
Compile .mqh

### ISSUE THREAD

**Issue by Waxavi** [KeisukeIwabuchi/compilemql4#2]
Hello, I appreciate this extension for VSCode, thank you!

I see compiling mqh doesn't work, would you please include it in a future update?

Edit: it seems it must be used by a .mq4 file, can't compile it alone like with the MT4 IDE.

Regards,

**Comment by KeisukeIwabuchi** [comment]
Thank you for contacting us.

This problem is caused by metaeditor.exe and metaeditor64.exe.

Therefore, it is difficult for me to solve.

Compile errors occur when you write old MQL4 code in mqh file.

Replacing the error part with MQL5 code will not cause an error.

e.g.  AccountNumber() -> AccountInfoInteger(ACCOUNT_LOGIN)

**Comment by Waxavi** [comment]
Ok, I'll try this out, thanks for your response.
